### ISSUE TITLE
Support Laravel-Data v3.x

### ISSUE THREAD

**Issue by jesseschutt** [lepikhinb/momentum-lock#2]
Hello! 

Now that [Laravel Data is on v3.x](https://github.com/spatie/laravel-data/releases/tag/3.0.0) can this package be updated to support it as well? 

Thank you!

**Comment by lepikhinb** [comment]
I'm gonna upgrade it asap. At the meantime, feel free to submit a PR :)

**Comment by jesseschutt** [comment]
PR #4 opened!
